using System.IO;
using Microsoft.CodeAnalysis;

namespace Dinghy.Magic;

public static class AssetRouter
{
    public static void RouteAsset(GeneratorExecutionContext context, AdditionalText t, string extention)
    {
        //var text = additionalFile.GetText();
        string source = $@"// <auto-generated/>

namespace Res
{{
    // {t.Path}
    public partial class {Path.GetFileNameWithoutExtension(t.Path)}
    {{
    }}
}}
";
        context.AddSource($"{Path.GetFileNameWithoutExtension(t.Path)}.g", source);
    }
}